# Generated by Django 5.2 on 2025-07-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlistitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
