# Generated by Django 5.2 on 2025-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
