# Generated by Django 5.2 on 2025-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
