# Generated by Django 5.2 on 2025-04-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_tran_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
