# Generated by Django 5.2 on 2025-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_logo_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='men', max_length=10),
        ),
    ]
